// Code generated by "stringer -type=jobType ."; DO NOT EDIT.

package storage

import "strconv"

const _jobType_name = "jobFlushjobGetBlockByIdjobGetBlockIdByNamejobSetNameToBlockIdjobSetStorageBlockStatusjobReferOrStoreBlockjobUpdateBlockIdRefCountjobUpdateBlockIdStorageRefCountjobStoreBlockjobQuit"

var _jobType_index = [...]uint8{0, 8, 23, 42, 61, 85, 105, 129, 160, 173, 180}

func (i jobType) String() string {
	if i < 0 || i >= jobType(len(_jobType_index)-1) {
		return "jobType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _jobType_name[_jobType_index[i]:_jobType_index[i+1]]
}
