// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fs.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	MissingIds           [][]byte `protobuf:"bytes,4,rep,name=missingIds,proto3" json:"missingIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Block) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetMissingIds() [][]byte {
	if m != nil {
		return m.MissingIds
	}
	return nil
}

type BlockName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockName) Reset()         { *m = BlockName{} }
func (m *BlockName) String() string { return proto.CompactTextString(m) }
func (*BlockName) ProtoMessage()    {}
func (*BlockName) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{1}
}
func (m *BlockName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockName.Unmarshal(m, b)
}
func (m *BlockName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockName.Marshal(b, m, deterministic)
}
func (dst *BlockName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockName.Merge(dst, src)
}
func (m *BlockName) XXX_Size() int {
	return xxx_messageInfo_BlockName.Size(m)
}
func (m *BlockName) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockName.DiscardUnknown(m)
}

var xxx_messageInfo_BlockName proto.InternalMessageInfo

func (m *BlockName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BlockId struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockId) Reset()         { *m = BlockId{} }
func (m *BlockId) String() string { return proto.CompactTextString(m) }
func (*BlockId) ProtoMessage()    {}
func (*BlockId) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{2}
}
func (m *BlockId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockId.Unmarshal(m, b)
}
func (m *BlockId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockId.Marshal(b, m, deterministic)
}
func (dst *BlockId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockId.Merge(dst, src)
}
func (m *BlockId) XXX_Size() int {
	return xxx_messageInfo_BlockId.Size(m)
}
func (m *BlockId) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockId.DiscardUnknown(m)
}

var xxx_messageInfo_BlockId proto.InternalMessageInfo

func (m *BlockId) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WantData             bool     `protobuf:"varint,2,opt,name=wantData,proto3" json:"wantData,omitempty"`
	WantMissing          bool     `protobuf:"varint,3,opt,name=wantMissing,proto3" json:"wantMissing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockRequest) Reset()         { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()    {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{3}
}
func (m *GetBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockRequest.Unmarshal(m, b)
}
func (m *GetBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRequest.Merge(dst, src)
}
func (m *GetBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockRequest.Size(m)
}
func (m *GetBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRequest proto.InternalMessageInfo

func (m *GetBlockRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetBlockRequest) GetWantData() bool {
	if m != nil {
		return m.WantData
	}
	return false
}

func (m *GetBlockRequest) GetWantMissing() bool {
	if m != nil {
		return m.WantMissing
	}
	return false
}

type MergeRequest struct {
	FromName             string   `protobuf:"bytes,1,opt,name=fromName,proto3" json:"fromName,omitempty"`
	ToName               string   `protobuf:"bytes,2,opt,name=toName,proto3" json:"toName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeRequest) Reset()         { *m = MergeRequest{} }
func (m *MergeRequest) String() string { return proto.CompactTextString(m) }
func (*MergeRequest) ProtoMessage()    {}
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{4}
}
func (m *MergeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeRequest.Unmarshal(m, b)
}
func (m *MergeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeRequest.Marshal(b, m, deterministic)
}
func (dst *MergeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeRequest.Merge(dst, src)
}
func (m *MergeRequest) XXX_Size() int {
	return xxx_messageInfo_MergeRequest.Size(m)
}
func (m *MergeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MergeRequest proto.InternalMessageInfo

func (m *MergeRequest) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *MergeRequest) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

type StoreRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Block                *Block   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{5}
}
func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (dst *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(dst, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StoreRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type SetNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNameRequest) Reset()         { *m = SetNameRequest{} }
func (m *SetNameRequest) String() string { return proto.CompactTextString(m) }
func (*SetNameRequest) ProtoMessage()    {}
func (*SetNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{6}
}
func (m *SetNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNameRequest.Unmarshal(m, b)
}
func (m *SetNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNameRequest.Marshal(b, m, deterministic)
}
func (dst *SetNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNameRequest.Merge(dst, src)
}
func (m *SetNameRequest) XXX_Size() int {
	return xxx_messageInfo_SetNameRequest.Size(m)
}
func (m *SetNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetNameRequest proto.InternalMessageInfo

func (m *SetNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetNameRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type MergeResult struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeResult) Reset()         { *m = MergeResult{} }
func (m *MergeResult) String() string { return proto.CompactTextString(m) }
func (*MergeResult) ProtoMessage()    {}
func (*MergeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{7}
}
func (m *MergeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeResult.Unmarshal(m, b)
}
func (m *MergeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeResult.Marshal(b, m, deterministic)
}
func (dst *MergeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeResult.Merge(dst, src)
}
func (m *MergeResult) XXX_Size() int {
	return xxx_messageInfo_MergeResult.Size(m)
}
func (m *MergeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeResult.DiscardUnknown(m)
}

var xxx_messageInfo_MergeResult proto.InternalMessageInfo

func (m *MergeResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SetNameResult struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNameResult) Reset()         { *m = SetNameResult{} }
func (m *SetNameResult) String() string { return proto.CompactTextString(m) }
func (*SetNameResult) ProtoMessage()    {}
func (*SetNameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{8}
}
func (m *SetNameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNameResult.Unmarshal(m, b)
}
func (m *SetNameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNameResult.Marshal(b, m, deterministic)
}
func (dst *SetNameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNameResult.Merge(dst, src)
}
func (m *SetNameResult) XXX_Size() int {
	return xxx_messageInfo_SetNameResult.Size(m)
}
func (m *SetNameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNameResult.DiscardUnknown(m)
}

var xxx_messageInfo_SetNameResult proto.InternalMessageInfo

func (m *SetNameResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ClearResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearResult) Reset()         { *m = ClearResult{} }
func (m *ClearResult) String() string { return proto.CompactTextString(m) }
func (*ClearResult) ProtoMessage()    {}
func (*ClearResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fs_c18b9569cf7849e8, []int{9}
}
func (m *ClearResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearResult.Unmarshal(m, b)
}
func (m *ClearResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearResult.Marshal(b, m, deterministic)
}
func (dst *ClearResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearResult.Merge(dst, src)
}
func (m *ClearResult) XXX_Size() int {
	return xxx_messageInfo_ClearResult.Size(m)
}
func (m *ClearResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearResult.DiscardUnknown(m)
}

var xxx_messageInfo_ClearResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Block)(nil), "fingon.iki.fi.tfhfs.Block")
	proto.RegisterType((*BlockName)(nil), "fingon.iki.fi.tfhfs.BlockName")
	proto.RegisterType((*BlockId)(nil), "fingon.iki.fi.tfhfs.BlockId")
	proto.RegisterType((*GetBlockRequest)(nil), "fingon.iki.fi.tfhfs.GetBlockRequest")
	proto.RegisterType((*MergeRequest)(nil), "fingon.iki.fi.tfhfs.MergeRequest")
	proto.RegisterType((*StoreRequest)(nil), "fingon.iki.fi.tfhfs.StoreRequest")
	proto.RegisterType((*SetNameRequest)(nil), "fingon.iki.fi.tfhfs.SetNameRequest")
	proto.RegisterType((*MergeResult)(nil), "fingon.iki.fi.tfhfs.MergeResult")
	proto.RegisterType((*SetNameResult)(nil), "fingon.iki.fi.tfhfs.SetNameResult")
	proto.RegisterType((*ClearResult)(nil), "fingon.iki.fi.tfhfs.ClearResult")
}

func init() { proto.RegisterFile("fs.proto", fileDescriptor_fs_c18b9569cf7849e8) }

var fileDescriptor_fs_c18b9569cf7849e8 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x6e, 0xb3, 0x76, 0x64, 0xd7, 0x6c, 0x14, 0x4f, 0x42, 0x25, 0x82, 0x2d, 0x18, 0x1e, 0xfa,
	0x14, 0xa1, 0xc1, 0x2f, 0x08, 0x08, 0x94, 0x87, 0x4e, 0xc2, 0x2b, 0x9a, 0x40, 0x42, 0xc8, 0x9d,
	0x9d, 0x12, 0xa5, 0x8d, 0x4b, 0xec, 0x0a, 0xed, 0xe7, 0xf2, 0x4f, 0x50, 0x2e, 0x69, 0x08, 0xc3,
	0x0d, 0x7b, 0xf3, 0xf9, 0xbb, 0xfb, 0xfc, 0xdd, 0x77, 0x97, 0x80, 0x9b, 0xe8, 0x70, 0x53, 0x28,
	0xa3, 0xc8, 0x69, 0x92, 0xe6, 0x4b, 0x95, 0x87, 0x69, 0x96, 0x86, 0x49, 0x1a, 0x9a, 0xe4, 0x7b,
	0xa2, 0xe9, 0x0d, 0x0c, 0xa3, 0x95, 0xba, 0xc9, 0xc8, 0x09, 0x38, 0xa9, 0x98, 0xf4, 0x83, 0xfe,
	0xd4, 0x63, 0x4e, 0x2a, 0xc8, 0x63, 0x38, 0xd4, 0x86, 0x9b, 0xad, 0x9e, 0x38, 0x41, 0x7f, 0x3a,
	0x64, 0x75, 0x44, 0x08, 0x0c, 0x04, 0x37, 0x7c, 0x72, 0x80, 0x99, 0x78, 0x26, 0x67, 0x00, 0xeb,
	0x54, 0xeb, 0x34, 0x5f, 0xc6, 0x42, 0x4f, 0x06, 0xc1, 0xc1, 0xd4, 0x63, 0xad, 0x1b, 0x7a, 0x0e,
	0x47, 0xf8, 0xc8, 0x25, 0x5f, 0xcb, 0x92, 0x20, 0xe7, 0x6b, 0x89, 0x4f, 0x1d, 0x31, 0x3c, 0xd3,
	0x27, 0xf0, 0x00, 0x13, 0x62, 0x71, 0x57, 0x07, 0xfd, 0x06, 0x0f, 0x3f, 0x48, 0x83, 0x28, 0x93,
	0x3f, 0xb6, 0x52, 0x9b, 0x7f, 0xa4, 0xfa, 0xe0, 0xfe, 0xe4, 0xb9, 0x79, 0x57, 0xca, 0x2a, 0xc5,
	0xba, 0xac, 0x89, 0x49, 0x00, 0xa3, 0xf2, 0x3c, 0xab, 0xc4, 0xa0, 0x6a, 0x97, 0xb5, 0xaf, 0x68,
	0x04, 0xde, 0x4c, 0x16, 0x4b, 0xb9, 0x63, 0xf7, 0xc1, 0x4d, 0x0a, 0xb5, 0xbe, 0xfc, 0xa3, 0xb1,
	0x89, 0x4b, 0x53, 0x8c, 0x42, 0xc4, 0x41, 0xa4, 0x8e, 0xe8, 0x1c, 0xbc, 0x2b, 0xa3, 0x8a, 0x86,
	0xc3, 0xd2, 0x23, 0x79, 0x05, 0xc3, 0x45, 0xd9, 0x05, 0x96, 0x8e, 0x2e, 0xfc, 0xd0, 0x32, 0x8e,
	0xb0, 0xea, 0xb3, 0x4a, 0xa4, 0x6f, 0xe0, 0xe4, 0x4a, 0x9a, 0xf2, 0x81, 0x2e, 0xde, 0xca, 0x0d,
	0xa7, 0x31, 0xec, 0x19, 0x8c, 0xea, 0x7e, 0xf4, 0x76, 0x85, 0x66, 0xa9, 0x0c, 0x0b, 0x5c, 0xe6,
	0xa8, 0x8c, 0x9e, 0xc3, 0x71, 0x43, 0x6a, 0x4d, 0x38, 0x86, 0xd1, 0xdb, 0x95, 0xe4, 0x45, 0x05,
	0x5f, 0xfc, 0x1a, 0x80, 0xf3, 0x5e, 0x93, 0x6b, 0x78, 0x84, 0xb7, 0x28, 0x50, 0xc7, 0x39, 0xda,
	0x71, 0xb6, 0xbf, 0x87, 0x12, 0xf7, 0x03, 0x2b, 0xde, 0x62, 0xa7, 0x3d, 0xc2, 0x60, 0xbc, 0x9b,
	0x6f, 0x2c, 0xa2, 0xdb, 0x7b, 0xf1, 0x3e, 0xdd, 0x8f, 0xc7, 0x02, 0x39, 0xbd, 0x1d, 0x67, 0x74,
	0x1b, 0x0b, 0xf2, 0xd2, 0x9a, 0x7f, 0x67, 0xad, 0xfc, 0x8e, 0x89, 0xd0, 0x1e, 0xf9, 0x0c, 0x63,
	0xb4, 0xb5, 0x51, 0x31, 0x57, 0xe4, 0xb9, 0xb5, 0xa2, 0xbd, 0x4d, 0x7b, 0x2c, 0x68, 0x0d, 0x88,
	0xf6, 0xc8, 0x57, 0x18, 0xd7, 0x23, 0x99, 0xab, 0xdd, 0x67, 0xf0, 0xc2, 0x5a, 0xf7, 0xf7, 0x3a,
	0xf8, 0xb4, 0x3b, 0xa9, 0xa6, 0x9f, 0x01, 0xe0, 0x72, 0x56, 0xdf, 0xb9, 0x5d, 0x73, 0x7b, 0x7b,
	0xff, 0x63, 0xc4, 0x47, 0x38, 0xfd, 0xb4, 0x59, 0x16, 0x5c, 0xd4, 0x56, 0xa8, 0xfc, 0x5a, 0xf2,
	0x8c, 0x74, 0xce, 0xa4, 0x9b, 0x32, 0x1a, 0x7c, 0x71, 0x36, 0x8b, 0xc5, 0x21, 0xfe, 0xa6, 0x5e,
	0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xce, 0xa8, 0xbe, 0x62, 0xb2, 0x04, 0x00, 0x00,
}
